Repository scania-digital-design-system/sdds-website, pull requests merged in 2019-12, with the labels that each got.

#11 Add a notification area
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/app.service.ts
  src/app/components/note/note.component.html
  src/app/components/note/note.component.scss
  src/app/components/note/note.component.ts
Labels: enhancement

#12 Add theme typing
  src/app/app.interface.ts
  src/app/components/color-list/color-list.component.html
  src/app/components/color-list/color-list.component.ts
  src/app/components/icon-list/icon-list.component.ts
  src/app/components/toggler/toggler.component.scss
Labels: enhancement

#13 Bumped version
  package.json
Labels: enhancement

#16 Fix for IE navigation problem
  src/app/app.component.scss
Labels: bug

#15 Changed data structure and relations to it
  src/app/app-routing.module.ts
  src/app/app.interface.ts
  src/app/components/main/main.component.ts
  src/app/components/navigation/navigation.component.html
  src/app/data/content.json
  src/app/data/templates.json
Labels: enhancement

#18 Remove angular favicon in corporate-ui-site
  src/index.html
Labels: Improvement

#20 Bumped version of corporate-ui and scania-theme
  README.md
  package-lock.json
  package.json
  src/app/app.interface.ts
  src/app/app.service.ts
  src/app/data/content.json
  src/main.ts
Labels: Improvement

#21 bump version
  package-lock.json
  package.json
Labels: Improvement

#25 Bump version 4.0.0
  package-lock.json
  package.json
Labels: Improvement
