Repository scania-digital-design-system/sdds-website, pull requests merged in 2020-01, with the labels that each got.

#28 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: Improvement

#29 Added templates for issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
Labels: Improvement

#27 Update migration docs
  src/app/data/content.json
Labels: Improvement

#30 Feature - Bump version corporate-ui and scania-theme
  package-lock.json
  package.json
Labels: Feature

#26 Navigating freezes in IE
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/app.pipe.ts
  src/app/app.service.ts
  src/app/components/header/header.component.scss
  src/app/components/main/main.component.scss
  src/app/components/note/note.component.html
  src/app/components/note/note.component.scss
  src/app/components/note/note.component.ts
  src/app/data/content.json
  src/styles.scss
Labels: Bug

#31 Improvement - Added example for links in typography and updated icons
  src/app/data/content.json
Labels: Improvement

#34 bump version
  package-lock.json
  package.json
Labels: Feature
