Repository scania-digital-design-system/sdds-website, pull requests merged in 2020-04, with the labels that each got.

#55 Code example component updated
  src/app/components/code-example/code-example.component.html
  src/app/components/code-example/code-example.component.scss
  src/app/components/code-example/code-example.component.ts
  src/app/components/page/page.component.scss
Labels: Improvement

#56 Fixed the resolution issues for icons and components list
  src/app/components/icon-list/icon-list.component.html
  src/app/components/main/main.component.html
  src/app/components/main/main.component.scss
  src/app/components/page/page.component.scss
Labels: Improvement

#57 Update corporate-ui and scania-theme
  package-lock.json
  package.json
Labels: Feature

#58 Feature/color page
  src/app/components/color-list/color-list.component.html
  src/app/components/color-list/color-list.component.scss
  src/app/components/color-list/color-list.component.ts
Labels: Feature

#61 Fix IE support for color list component
  src/app/components/color-list/color-list.component.ts
Labels: Bug

#59 Content/add cui instruction and new color
  package.json
  src/app/data/content.json
  src/app/data/navigation.json
  src/app/data/templates.json
Labels: Content

#62 Bump scania-theme
  package-lock.json
  package.json
Labels: Improvement

#64 Small fix for the IE problem not showing content
  src/app/components/page/page.component.ts
Labels: Bug

#63 Add timestamp
  fetchData.js
  src/app/app-routing.module.ts
  src/app/app.pipe.ts
  src/app/components/page/page.component.scss
Labels: Improvement

#65 Added style for FAQ page
  src/app/components/page/page.component.scss
Labels: Improvement

#66 Refactor the page component in SDDS
  src/app/components/page/page.component.ts
Labels: Improvement
