Repository scania-digital-design-system/sdds-website, pull requests merged in 2020-05, with the labels that each got.

#67 Content-add new content faq & update page title
  src/app/app.component.html
  src/app/data/content.json
  src/app/data/navigation.json
  src/app/data/templates.json
Labels: Content

#68 bump version of SDDS
  package-lock.json
  package.json
  src/app/data/content.json
Labels: Feature

#69 bump data and version
  package-lock.json
  package.json
Labels: Feature

#70 Code example component bug
  src/app/components/code-example/code-example.component.html
Labels: Bug

#72 Section for the content added from cms
  fetchData.js
  src/app/components/code-example/code-example.component.html
  src/app/components/page/page.component.ts
Labels: Improvement
