Repository scania-digital-design-system/sdds-website, pull requests merged in 2020-06, with the labels that each got.

#73 Update FAQ
  src/app/data/content.json
Labels: Content

#71 Improvement/improve tab
  fetchData.js
  src/app/components/code-example/code-example.component.html
  src/app/components/main/main.component.scss
  src/app/components/page/page.component.ts
Labels: Improvement

#75 Update content and corporate ui package
  package-lock.json
  package.json
  src/app/data/content.json
  src/app/data/navigation.json
  src/app/data/templates.json
Labels: Content

#77 Solving issue with redirect endless loop
  src/404.html
Labels: Bug

#78 Feature - tab link url
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/app.pipe.ts
  src/app/components/main/main.component.scss
  src/app/components/page/page.component.html
  src/app/components/page/page.component.ts
  src/app/components/page/tab-content/tab-content.component.ts
Labels: Feature

#80 Fix bug in home URL
  src/app/components/main/main.component.ts
Labels: Bug

#79 Added FAQ about bootstrap event
  src/app/data/content.json
Labels: Content
