Repository scania-digital-design-system/sdds-website, pull requests merged in 2020-12, with the labels that each got.

#119 Removed fluid grid
  src/app/components/page/page.component.html
Labels: Improvement

#120 Improvement - page detail
  fetchData.js
  package-lock.json
  package.json
  scania-theme-light-1.2.0.tgz
  src/app/app-routing.module.ts
  src/app/app-vars.scss
  src/app/components/code-example/code-example.component.html
  src/app/components/content-header/content-header.component.html
  src/app/components/content-header/content-header.component.scss
  src/app/components/header/header.component.scss
  src/app/components/main/main.component.scss
  src/app/components/page/page.component.html
  src/app/components/page/page.component.scss
  src/app/components/page/page.component.ts
  src/app/components/page/tab-content/tab-content.component.html
  src/app/components/page/tab-content/tab-content.component.ts
Labels: Improvement

#122 Add official SDDS package
  package-lock.json
  package.json
  scania-components-4.2.0.tgz
  scania-theme-light-1.2.0.tgz
  src/app/app.service.ts
  src/app/data/content.json
  src/app/data/navigation.json
  src/main.ts
Labels: Feature

#123 Feature- sidebar navigation
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.service.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/components/main/main.component.html
  src/app/components/main/main.component.ts
  src/app/components/navigation/navigation.component.html
  src/app/components/navigation/navigation.component.scss
  src/app/components/navigation/navigation.component.ts
  src/app/components/page/page.component.html
  src/app/components/page/page.component.ts
  src/app/components/page/tab-content/tab-content.component.ts
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Feature

#131 code-snippet styling added
  src/app/components/page/page.component.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Improvement

#126 Feature/cards
  fetchData.js
  src/app/app.component.scss
  src/app/components/page/page.component.scss
  src/app/components/page/styles/anchor-menu.scss
  src/app/components/page/styles/code-tab.scss
  src/app/components/page/styles/page-templates.scss
  src/app/components/page/styles/tab-content.scss
  src/app/components/page/styles/tab-nav.scss
  src/app/components/page/styles/templates/card.scss
  src/app/components/page/styles/templates/images.scss
  src/app/components/page/styles/templates/modal.scss
  src/app/components/page/tab-content/tab-content.component.ts
Labels: Improvement

#127 Feature/dos donts
  fetchData.js
  src/app/components/page/page.component.scss
  src/app/components/page/styles/code-tab.scss
  src/app/components/page/styles/page-templates.scss
  src/app/components/page/styles/templates/code.scss
  src/app/components/page/styles/templates/do-dont.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/assets/images/icon-do.svg
  src/assets/images/icon-dont.svg
Labels: Feature

#135 Improvements - A lot of different fixes (grid,images,full width, do and donts)
  src/app/components/page/page.component.html
  src/app/components/page/styles/anchor-menu.scss
  src/app/components/page/styles/templates/do-dont.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Improvement

#137 Improvement - Fix for anchor position
  src/app/app-vars.scss
  src/app/components/page/page.component.html
  src/app/components/page/styles/anchor-menu.scss
  src/app/components/page/styles/templates/code.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/app/components/page/tab-content/tab-content.component.ts
  src/app/data/content.json
Labels: Improvement

#136 Improvement/general spacing
  fetchData.js
  src/app/components/page/page.component.scss
  src/app/components/page/styles/tab-content.scss
  src/app/components/page/styles/templates/card.scss
  src/app/components/page/styles/templates/images.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Improvement

#138 Improvement - landing page
  fetchData.js
  src/app/app-routing.module.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.scss
  src/app/components/card/card.component.ts
  src/app/components/content-header/content-header.component.html
  src/app/components/content-header/content-header.component.ts
  src/app/components/main/main.component.scss
  src/app/components/page/landing-page/landing-page.component.html
  src/app/components/page/landing-page/landing-page.component.ts
  src/app/components/page/page.component.html
  src/app/components/page/page.component.scss
  src/app/components/page/styles/page-templates.scss
  src/app/components/page/styles/tab-content.scss
  src/app/components/page/styles/templates/images.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/app/components/page/tab-content/tab-content.component.ts
  src/assets/images/arrow-right.svg
Labels: Feature

#142 Add footer component
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/footer/footer.component.ts
  src/app/components/main/main.component.html
  src/app/components/main/main.component.scss
  src/app/components/main/main.component.ts
Labels: Improvement

#170 Fix tab nav scrolling on mobile view
  src/app/components/page/styles/tab-nav.scss
Labels: Improvement

#156 Pictogram page
  src/app/components/icon-list/icon-list.component.html
  src/app/components/icon-list/icon-list.component.scss
  src/app/components/icon-list/icon-list.component.ts
  src/app/components/page/page.component.html
  src/app/components/page/page.component.scss
  src/app/components/page/page.component.ts
  src/app/components/page/tab-content/tab-content.component.html
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Improvement

#178 Fix for bug with multi column
  src/app/components/page/tab-content/tab-content.component.html
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Bug

#181 Share link thumbnail
  src/index.html
Labels: Improvement

#180 Fix on first level nav page >> Contribution page
  src/app/components/page/page.component.html
Labels: Improvement

#173 Custom Scrollbar
  src/app/app.component.scss
  src/app/components/main/main.component.scss
  src/app/components/navigation/navigation.component.scss
  src/app/components/page/styles/page-templates.scss
Labels: Improvement

#188 move scania symbol temp
  src/app/components/header/header.component.scss
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Improvement

#189 updated content
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Improvement

#192 Add link to let us know button on landing page
  src/app/components/content-header/content-header.component.scss
  src/app/components/footer/footer.component.html
  src/app/components/page/landing-page/landing-page.component.html
  src/app/components/page/page.component.scss
Labels: Bug

#194 fix arrow for in safari
  src/app/app-routing.module.ts
  src/app/components/page/styles/page-templates.scss
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Bug

#199 Add scroll to top button
  src/app/app.component.scss
  src/app/components/main/main.component.html
  src/app/components/main/main.component.scss
  src/app/components/main/main.component.ts
Labels: Feature
