Repository scania-digital-design-system/sdds-website, pull requests merged in 2020-09, with the labels that each got.

#84 Add color fix for code section in getting started
  src/app/components/page/page.component.scss
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Improvement

#90 Improvement - refactoring and clean up for site
  README.md
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/components/modal/modal.component.html
  src/app/components/modal/modal.component.ts
  src/app/components/toggler/toggler.component.html
  src/app/components/toggler/toggler.component.scss
  src/app/components/toggler/toggler.component.ts
Labels: Improvement

#95 Update content with new links
  src/app/data/content.json
Labels: Content

#94 Bug - Handling error if there is a theme without icons
  src/app/components/icon-list/icon-list.component.ts
Labels: Bug

#96 improvement - updated scania-theme and corporate-ui version
  README.md
  package-lock.json
  package.json
Labels: Improvement

#88 Improvement - Adding table with properties and attribute for each web-component
  fetchData.js
  src/app/app-routing.module.ts
  src/app/components/code-example/code-example.component.html
  src/app/components/code-example/code-example.component.ts
  src/app/components/code-props/code-props.component.html
  src/app/components/code-props/code-props.component.scss
  src/app/components/code-props/code-props.component.ts
  src/app/components/page/tab-content/tab-content.component.ts
Labels: Improvement

#97 Improvement - icon page main template
  fetchData.js
  src/app/app.interface.ts
  src/app/components/code-example/code-example.component.html
  src/app/components/code-props/code-props.component.ts
  src/app/components/icon-list/icon-list.component.html
  src/app/components/icon-list/icon-list.component.ts
  src/app/components/page/page.component.html
  src/app/components/page/page.component.scss
  src/app/components/page/page.component.ts
  src/app/components/page/tab-content/tab-content.component.html
  src/app/components/page/tab-content/tab-content.component.ts
Labels: Improvement

#98 Solved bug with scroll in edge
  src/app/app.component.scss
  src/app/components/main/main.component.scss
  src/app/components/page/page.component.scss
Labels: Bug

#101 Feature - Update version and content
  package-lock.json
  package.json
  src/app/data/content.json
Labels: Feature
