Repository scania-digital-design-system/sdds-website, pull requests merged in 2021-01, with the labels that each got.

#203 Improvement/table colour and size
  fetchData.js
  src/app/components/page/page.component.scss
  src/app/components/page/styles/templates/tables.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/app/data/content.json
Labels: Improvement, Website

#202 Improvement - Updated references, Banner landingpage placement, readme update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package-lock.json
  package.json
  src/app/app.interface.ts
  src/app/components/code-props/code-props.component.ts
  src/app/components/header/header.component.scss
  src/app/components/icon-list/icon-list.component.ts
  src/app/components/page/landing-page/landing-page.component.html
  src/app/components/page/landing-page/landing-page.component.ts
  src/app/components/page/page.component.html
  src/app/components/page/page.component.scss
  src/app/components/page/styles/page-templates.scss
  src/app/data/content.json
Labels: Improvement, Website

#200 Improvement/add active on anchor
  src/app/components/page/styles/anchor-menu.scss
  src/app/components/page/tab-content/tab-content.component.html
  src/app/components/page/tab-content/tab-content.component.ts
Labels: Improvement, Website

#210 Feature/search website
  fetchData.js
  src/app/app.module.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/components/search-list/search-list.component.html
  src/app/components/search-list/search-list.component.scss
  src/app/components/search-list/search-list.component.ts
  src/app/components/search-list/search.service.ts
  src/index.html
Labels: Feature, Website

#215 Added new scania package name
  README.md
  package-lock.json
  package.json
  src/app/app.component.scss
  src/app/app.interface.ts
  src/app/app.service.ts
  src/app/components/code-props/code-props.component.ts
  src/app/components/content-header/content-header.component.scss
  src/app/components/footer/footer.component.scss
  src/app/components/header/header.component.scss
  src/app/components/icon-list/icon-list.component.scss
  src/app/components/page/page.component.scss
  src/app/components/page/styles/anchor-menu.scss
  src/app/components/page/styles/templates/code.scss
  src/app/components/page/styles/templates/tables.scss
  src/main.ts
Labels: Improvement

#214 AB#251 Solves issue with missing bootstrap styling
  package-lock.json
  package.json
  src/app/components/icon-list/icon-list.component.ts
  src/app/components/search-list/search-list.component.scss
  src/styles.scss
  src/tobedeprecated.scss
Labels: Feature, Website

#216 Fix icon link github
  src/app/components/icon-list/icon-list.component.ts
Labels: Bug, Website
