Repository scania-digital-design-system/sdds-website, pull requests merged in 2021-03, with the labels that each got.

#233 Code-snippet component
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/components/code-example/code-example.component.html
  src/app/components/code-example/code-example.component.ts
  src/app/components/code-example/code-snippet/code-snippet.component.html
  src/app/components/code-example/code-snippet/code-snippet.component.scss
  src/app/components/code-example/code-snippet/code-snippet.component.ts
  src/app/components/code-props/code-props.component.html
  src/app/components/code-props/code-props.component.scss
  src/app/components/code-props/code-props.component.ts
  src/app/components/page/page.component.scss
Labels: Feature, Website

#234 Content/update content from sprint 4
  package-lock.json
  package.json
  src/app/data/content.json
  src/app/data/navigation.json
Labels: Content

#238 Add issue as a task in azure
  .github/workflows/azuredevops-issue.yml
Labels: Improvement, Website

#241 Update image size
  src/app/data/content.json
Labels: Content

#240 AB#359 Update new size for dos and donts
  fetchData.js
  src/app/components/page/page.component.html
  src/app/components/page/tab-content/tab-content.component.html
Labels: Improvement, Website
